[workspace]
resolver = "2"

members = [
  "packages/react/transform/swc-plugin-compat",
  "packages/react/transform/swc-plugin-react-lynx",
]

[profile.release]
codegen-units = 1
# debug = true
lto = true
opt-level = "s"
